defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_dev
test:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_test
production:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_pro
