development:
  address: <%= ENV['SPHINX_HOST_ADDR'] %>
  mysql41: <%= ENV['SPHINX_HOST_PORT'] %>
  configuration_file: <%= ENV['SPHINX_FILE_LOCATION'] %>/config/development.sphinx.conf
  min_infix_len: 2

production:
  address: <%= ENV['SPHINX_HOST_ADDR'] %>
  mysql41: <%= ENV['SPHINX_HOST_PORT'] %>
  configuration_file: <%= ENV['SPHINX_FILE_LOCATION'] %>/sphinx.conf
  min_infix_len: 2

